backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/photos"
public_folder: "/photos"

collections:
  - name: "series"
    label: "Séries"
    folder: "content/series"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Texte", name: "body", widget: "markdown" }
      - label: "Photos"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "url", widget: "image" }
          - {
              label: "Titre (optionnel)",
              name: "title",
              widget: "string",
              required: false,
            }
          - {
              label: "Légende (optionnel)",
              name: "caption",
              widget: "text",
              required: false,
            }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }

      - label: "Biographie"
        name: "biographie"
        file: "content/pages/biographie.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
