backend:
  name: git-gateway
  branch: main

media_folder: "public/photos"
public_folder: "/photos"

collections:
  - name: "series"
    label: "Séries"
    folder: "content/series"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Texte", name: "body", widget: "markdown" }
      - label: "Photos"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "url", widget: "image" }
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Légende", name: "caption", widget: "text" }
